services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    image: vitruve
    container_name: server
    restart: always
    ports:
      - "5000:3000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
